--- #YAML:1.0
name: Solaris-Disk-VTOC
version: 0.01
author:
  - Jérôme Fenal E<lt>jfenal@free.frE<gt>
abstract: ~
license: perl
requires:
  perl: 5.6.1
provides:
  Solaris::Disk::VTOC:
    file: lib/Solaris/Disk/VTOC.pm
    version: 0.01
generated_by: Module::Build version 0.25
